1. ANIMAL_INS 전체 테이블 조회
SELECT * FROM ANIMAL_INS

2. ANIMAL_ID, NAME 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS

3. INTAKE_CONDITION 이 Aged가 아닌 컬럼 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'

4. ANIMAL_ID 순으로 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID ASC