1.전체 테이블 출력
SELECT * FROM ANIMAL_INS 

2.아이디와 이름 출력
SELECT ANIMAL_ID
         , NAME
FROM ANIMAL_INS

3.아픈 동물만 출력
SELECT ANIMAL_ID
       , NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'

4.아이디 순으로 조회
SELECT ANIMAL_ID
        , NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID ASC